### ISSUE TITLE
codigo repetido

### ISSUE THREAD

**Issue by asmx1986** [f-pochat/TpProg2#2]
https://github.com/f-pochat/TpProg2/blob/11dbe9c717bd6483b81fde8d7e59ef9b7a064ffb/src/com/Users/UserWriterReader.java#L53

chicos fijense q hay codigo repetido q pueden simplificar si hacen una abstraccion para la lectura de archivos, pueden hacer un objeto que lea todo y te retorne un array de objetos usando generics, o al menos un arraylist de arraylist de strings (como una matriz, o tmb conocido como datatables)

**Comment by f-pochat** [comment]
El codigo repetido lo entiendo. Pero esta mal que devolvamos un hashmap?
